package net.kapitencraft.enchantments_plus.data_gen;

import net.kapitencraft.enchantments_plus.EnchantmentsPlusMod;
import net.kapitencraft.enchantments_plus.ModTags;
import net.kapitencraft.kap_lib.core.tags.ExtraTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.EnchantmentTagsProvider;
import net.minecraft.tags.EnchantmentTags;
import net.minecraft.world.item.enchantment.Enchantments;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModEnchantmentTagsProvider extends EnchantmentTagsProvider {
    public ModEnchantmentTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, EnchantmentsPlusMod.MOD_ID, existingFileHelper);
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {
        tag(EnchantmentTags.TREASURE).add(
                ModEnchantments.BASALT_WALKER,
                ModEnchantments.BLOCK_BREATHER,
                ModEnchantments.ENDURANCE,
                ModEnchantments.ENLIGHTENMENT,
                ModEnchantments.PROTECTIVE_COVER,
                ModEnchantments.RESILIENCE,
                ModEnchantments.TRANSYLVANIAN,
                ModEnchantments.WIND_BLESSING,
                ModEnchantments.DIVINE_GIFT,
                ModEnchantments.SLEEPY,
                ModEnchantments.FLASH,
                ModEnchantments.REPLENISH,
                ModEnchantments.DELICATE,
                ModEnchantments.COMBAT_KNOWLEDGE,
                ModEnchantments.BLOOD_THIRST,
                ModEnchantments.AIM,
                ModEnchantments.OVERLOAD,
                ModEnchantments.SCAVENGER,
                ModEnchantments.HEALTH_MENDING
        );
        tag(EnchantmentTags.IN_ENCHANTING_TABLE).add(
                ModEnchantments.FIRM_STAND,
                ModEnchantments.KANGAROO,
                ModEnchantments.LONG_LEGS,
                ModEnchantments.MAGIC_PROTECTION,
                ModEnchantments.TRUE_PROTECTION,
                ModEnchantments.REJUVENATE,
                ModEnchantments.THORNY,
                ModEnchantments.SMELTING_TOUCH,
                ModEnchantments.BACK_STAB,
                ModEnchantments.ENDER_SLAYER,
                ModEnchantments.JUSTICE,
                ModEnchantments.ARMOR_SHREDDING,
                ModEnchantments.FIRST_STRIKE,
                ModEnchantments.TRIPLE_STRIKE,
                ModEnchantments.ELVISH_MASTERY,
                ModEnchantments.FAST_ARROWS,
                ModEnchantments.CHILLING,
                ModEnchantments.FROZEN_ARROWS,
                ModEnchantments.CRITICAl,
                ModEnchantments.SCAVENGER,
                ModEnchantments.TWO_HANDED,
                ModEnchantments.EXPERIENCED,
                ModEnchantments.COMPACTING,
                ModEnchantments.EXECUTE,
                ModEnchantments.PROSECUTE
        );
        tag(EnchantmentTags.TRADEABLE).add(
                ModEnchantments.BLOCK_BREATHER,
                ModEnchantments.ENDER_FRIEND,
                ModEnchantments.ENDURANCE,
                ModEnchantments.ENLIGHTENMENT,
                ModEnchantments.EXTINGUISH,
                ModEnchantments.FIRM_STAND,
                ModEnchantments.GROWTH,
                ModEnchantments.INSOMNIA,
                ModEnchantments.KANGAROO,
                ModEnchantments.LONG_LEGS,
                ModEnchantments.MAGIC_PROTECTION,
                ModEnchantments.REJUVENATE,
                ModEnchantments.RESILIENCE,
                ModEnchantments.SLEEPY,
                ModEnchantments.THORNY,
                ModEnchantments.TRUE_PROTECTION,
                ModEnchantments.CHROMATIC,
                ModEnchantments.DELICATE,
                ModEnchantments.FLASH,
                ModEnchantments.LUMBERJACK,
                ModEnchantments.MAGMATIC,
                ModEnchantments.REPLENISH,
                ModEnchantments.SMELTING_TOUCH,
                ModEnchantments.VEIN_MINER,
                ModEnchantments.BACK_STAB,
                ModEnchantments.BLOOD_THIRST,
                ModEnchantments.CHILLING,
                ModEnchantments.ENDER_SLAYER,
                ModEnchantments.GIANT_KILLER,
                ModEnchantments.JUSTICE,
                ModEnchantments.LIGHTNING_LORD,
                ModEnchantments.NECROTIC_TOUCH,
                ModEnchantments.POISONOUS_BLADE,
                ModEnchantments.FIRST_STRIKE,
                ModEnchantments.TRIPLE_STRIKE,
                ModEnchantments.ARMOR_SHREDDING,
                ModEnchantments.CHAIN_LIGHTNING,
                ModEnchantments.AIM,
                ModEnchantments.ELVISH_MASTERY,
                ModEnchantments.FAST_ARROWS,
                ModEnchantments.FROZEN_ARROWS,
                ModEnchantments.OVERLOAD,
                ModEnchantments.PRECISION,
                ModEnchantments.SNIPE,
                ModEnchantments.CRITICAl,
                ModEnchantments.DIVINE_GIFT,
                ModEnchantments.SCAVENGER,
                ModEnchantments.TWO_HANDED,
                ModEnchantments.COMPACTING,
                ModEnchantments.EXPERIENCED,
                ModEnchantments.HEALTH_MENDING,
                ModEnchantments.TELEKINESIS
        );
        tag(EnchantmentTags.ON_MOB_SPAWN_EQUIPMENT).add(
                ModEnchantments.BLOCK_BREATHER,
                ModEnchantments.FIRM_STAND,
                ModEnchantments.GLUTTONOUS,
                ModEnchantments.GROWTH,
                ModEnchantments.MAGIC_PROTECTION,
                ModEnchantments.REJUVENATE,
                ModEnchantments.THORNY,
                ModEnchantments.TRANSYLVANIAN,
                ModEnchantments.TRUE_PROTECTION,
                ModEnchantments.MAGMATIC,
                ModEnchantments.SILENT_HARVEST,
                ModEnchantments.SMELTING_TOUCH,
                ModEnchantments.BACK_STAB,
                ModEnchantments.BLOOD_THIRST,
                ModEnchantments.CHILLING,
                ModEnchantments.GIANT_KILLER,
                ModEnchantments.LIGHTNING_LORD,
                ModEnchantments.NECROTIC_TOUCH,
                ModEnchantments.FIRST_STRIKE,
                ModEnchantments.TRIPLE_STRIKE,
                ModEnchantments.VENOMOUS,
                ModEnchantments.ARMOR_SHREDDING,
                ModEnchantments.ELVISH_MASTERY,
                ModEnchantments.FAST_ARROWS,
                ModEnchantments.OVERLOAD,
                ModEnchantments.SNIPE,
                ModEnchantments.CRITICAl,
                ModEnchantments.EXPERIENCED,
                ModEnchantments.TELEKINESIS
        );
        tag(EnchantmentTags.ON_RANDOM_LOOT).add(
                ModEnchantments.BASALT_WALKER,
                ModEnchantments.BLOCK_BREATHER,
                ModEnchantments.BONK,
                ModEnchantments.ENDER_FRIEND,
                ModEnchantments.ENDURANCE,
                ModEnchantments.ENLIGHTENMENT,
                ModEnchantments.EXTINGUISH,
                ModEnchantments.FIRM_STAND,
                ModEnchantments.GLUTTONOUS,
                ModEnchantments.GROWTH,
                ModEnchantments.HEAVY_PLATING,
                ModEnchantments.INSOMNIA,
                ModEnchantments.KANGAROO,
                ModEnchantments.LONG_LEGS,
                ModEnchantments.MAGIC_PROTECTION,
                ModEnchantments.PROTECTIVE_COVER,
                ModEnchantments.REJUVENATE,
                ModEnchantments.RESILIENCE,
                ModEnchantments.SLEEPY,
                ModEnchantments.THORNY,
                ModEnchantments.TRANSYLVANIAN,
                ModEnchantments.TRUE_PROTECTION,
                ModEnchantments.CHROMATIC,
                ModEnchantments.DELICATE,
                ModEnchantments.FLASH,
                ModEnchantments.LUMBERJACK,
                ModEnchantments.MAGMATIC,
                ModEnchantments.REPLENISH,
                ModEnchantments.SILENT_HARVEST,
                ModEnchantments.SMELTING_TOUCH,
                ModEnchantments.VEIN_MINER,
                ModEnchantments.BACK_STAB,
                ModEnchantments.BLOOD_THIRST,
                ModEnchantments.CHILLING,
                ModEnchantments.COMBAT_KNOWLEDGE,
                ModEnchantments.ENDER_SLAYER,
                ModEnchantments.GIANT_KILLER,
                ModEnchantments.JUSTICE,
                ModEnchantments.LIGHTNING_LORD,
                ModEnchantments.NECROTIC_TOUCH,
                ModEnchantments.POISONOUS_BLADE,
                ModEnchantments.FIRST_STRIKE,
                ModEnchantments.TRIPLE_STRIKE,
                ModEnchantments.VENOMOUS,
                ModEnchantments.ARMOR_SHREDDING,
                ModEnchantments.CHAIN_LIGHTNING,
                ModEnchantments.AIM,
                ModEnchantments.ELVISH_MASTERY,
                ModEnchantments.FAST_ARROWS,
                ModEnchantments.FROZEN_ARROWS,
                ModEnchantments.OVERLOAD,
                ModEnchantments.PRECISION,
                ModEnchantments.SNIPE,
                ModEnchantments.WIND_BLESSING,
                ModEnchantments.CRITICAl,
                ModEnchantments.DIVINE_GIFT,
                ModEnchantments.INFERNO,
                ModEnchantments.SCAVENGER,
                ModEnchantments.TWO_HANDED,
                ModEnchantments.COMPACTING,
                ModEnchantments.EXPERIENCED,
                ModEnchantments.HEALTH_MENDING,
                ModEnchantments.TELEKINESIS,
                ModEnchantments.EXECUTE,
                ModEnchantments.PROSECUTE
        );
        tag(EnchantmentTags.ON_TRADED_EQUIPMENT).add(
                ModEnchantments.BLOCK_BREATHER,
                ModEnchantments.ENDER_FRIEND,
                ModEnchantments.ENLIGHTENMENT,
                ModEnchantments.GLUTTONOUS,
                ModEnchantments.GROWTH,
                ModEnchantments.KANGAROO,
                ModEnchantments.REJUVENATE,
                ModEnchantments.SLEEPY,
                ModEnchantments.CHROMATIC,
                ModEnchantments.LUMBERJACK,
                ModEnchantments.MAGMATIC,
                ModEnchantments.SMELTING_TOUCH,
                ModEnchantments.BACK_STAB,
                ModEnchantments.BLOOD_THIRST,
                ModEnchantments.ENDER_SLAYER,
                ModEnchantments.JUSTICE,
                ModEnchantments.FIRST_STRIKE,
                ModEnchantments.TRIPLE_STRIKE,
                ModEnchantments.ARMOR_SHREDDING,
                ModEnchantments.ELVISH_MASTERY,
                ModEnchantments.FAST_ARROWS,
                ModEnchantments.PRECISION,
                ModEnchantments.CRITICAl,
                ModEnchantments.DIVINE_GIFT,
                ModEnchantments.SCAVENGER,
                ModEnchantments.TWO_HANDED,
                ModEnchantments.COMPACTING,
                ModEnchantments.EXPERIENCED,
                ModEnchantments.TELEKINESIS,
                ModEnchantments.EXECUTE,
                ModEnchantments.PROSECUTE
        );
        tag(EnchantmentTags.TOOLTIP_ORDER).addTags(
                ExtraTags.Enchantments.ULTIMATE
        );
        tag(ExtraTags.Enchantments.ULTIMATE).add(
                ModEnchantments.BONK,
                ModEnchantments.GLUTTONOUS,
                ModEnchantments.HEAVY_PLATING,
                ModEnchantments.INFERNO,
                ModEnchantments.CHAIN_LIGHTNING,
                ModEnchantments.WIND_BLESSING,
                ModEnchantments.COMBAT_KNOWLEDGE,
                ModEnchantments.FATAL_TEMPO
        );
        tag(EnchantmentTags.CURSE).add(
                ModEnchantments.INSOMNIA,
                ModEnchantments.CHROMATIC,
                ModEnchantments.MAGMATIC
        );
        tag(ModTags.Enchantments.MINING_DROPS_EXCLUSIVE).add(
                Enchantments.SILK_TOUCH,
                ModEnchantments.SMELTING_TOUCH
        );
        tag(ModTags.Enchantments.STRIKE_EXCLUSIVE).add(
                ModEnchantments.FIRST_STRIKE,
                ModEnchantments.TRIPLE_STRIKE
        );
        tag(ModTags.Enchantments.EXECUTION_EXCLUSIVE).add(
                ModEnchantments.EXECUTE,
                ModEnchantments.PROSECUTE
        );
        tag(EnchantmentTags.ARMOR_EXCLUSIVE).add(
                ModEnchantments.MAGIC_PROTECTION,
                ModEnchantments.TRUE_PROTECTION
        );
    }
}
